TARGET_BOARD_PLATFORM := rk3588
TARGET_BOARD_PLATFORM_GPU := mali-G610
TARGET_BOARD_HARDWARE := rk30board
TARGET_RK_GRALLOC_VERSION := 4
BOARD_USE_DRM := true

PRODUCT_HAVE_RKVPU := true

# ALLOW_MISSING_DEPENDENCIES := true
BUILD_BROKEN_ELF_PREBUILT_PRODUCT_COPY_FILES := true

include device/rockchip/common/gralloc.device.mk